import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { CustomAdminNav } from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Monitorme',
  description: 'Generated by create next app',
  icons: {
    icon: '/svg/icon.svg'
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div></div>
        <div>
          {children}
        </div>
        <div>
        </div>
      </body>
    </html>
  )
}

