import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
<<<<<<< HEAD
import { CustomAdminNav } from '@/components'
=======
>>>>>>> bcab0d982a8c651f21ea2ebebe087963209ce63d

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
<<<<<<< HEAD
  title: 'Monitorme',
  description: 'Generated by create next app',
  icons: {
    icon: '/svg/icon.svg'
  }
=======
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> bcab0d982a8c651f21ea2ebebe087963209ce63d
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div></div>
<<<<<<< HEAD
        <div>
          {children}
        </div>
        <div>
=======
        <div className='my-10 mx-14'>
          {children}
        </div>
        <div>

>>>>>>> bcab0d982a8c651f21ea2ebebe087963209ce63d
        </div>
      </body>
    </html>
  )
}

